package output

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/abrahamakinwale/PROJECTS/subdiscover/pkg/httpprobe"
	"github.com/abrahamakinwale/PROJECTS/subdiscover/pkg/resolver"
)

// ScanReport is the full structured output
type ScanReport struct {
	Meta       Meta                      `json:"meta"`
	Subdomains []SubdomainEntry          `json:"subdomains"`
	HTTP       []HTTPEntry               `json:"http_live"`
	Assets     *resolver.AssetResult     `json:"assets"`
	Stats      Stats                     `json:"stats"`
}

type Meta struct {
	Tool      string    `json:"tool"`
	Version   string    `json:"version"`
	Copyright string    `json:"copyright"`
	Domain    string    `json:"domain"`
	ScanTime  time.Time `json:"scan_time"`
	Duration  string    `json:"duration"`
}

type SubdomainEntry struct {
	Subdomain string   `json:"subdomain"`
	IPs       []string `json:"ips"`
	IPv6      []string `json:"ipv6,omitempty"`
	CNAMEs    []string `json:"cnames,omitempty"`
	IsCDN     bool     `json:"is_cdn"`
}

type HTTPEntry struct {
	URL         string   `json:"url"`
	Subdomain   string   `json:"subdomain"`
	StatusCode  int      `json:"status_code"`
	Title       string   `json:"title,omitempty"`
	Server      string   `json:"server,omitempty"`
	Technologies []string `json:"technologies,omitempty"`
	IsHTTPS     bool     `json:"is_https"`
}

type Stats struct {
	TotalSubdomains int `json:"total_subdomains"`
	LiveHTTP        int `json:"live_http"`
	CDNCount        int `json:"cdn_count"`
	IPv6Count       int `json:"ipv6_count"`
}

func BuildReport(domain string, start time.Time, results []*resolver.Result, httpResults []*httpprobe.Result, assets *resolver.AssetResult) *ScanReport {
	report := &ScanReport{
		Meta: Meta{
			Tool:      "SubDiscover",
			Version:   "2.0.0",
			Copyright: "© 2026 Akid's Global Cyber Security Tools",
			Domain:    domain,
			ScanTime:  start,
			Duration:  time.Since(start).Round(time.Millisecond).String(),
		},
		Assets: assets,
	}

	var cdnCount, ipv6Count int
	for _, r := range results {
		entry := SubdomainEntry{
			Subdomain: r.Subdomain,
			IPs:       r.IPs,
			IPv6:      r.IPv6s,
			CNAMEs:    r.CNAMEs,
			IsCDN:     r.IsCDN,
		}
		report.Subdomains = append(report.Subdomains, entry)
		if r.IsCDN {
			cdnCount++
		}
		if len(r.IPv6s) > 0 {
			ipv6Count++
		}
	}

	for _, h := range httpResults {
		if h.IsAlive {
			report.HTTP = append(report.HTTP, HTTPEntry{
				URL:          h.URL,
				Subdomain:    h.Subdomain,
				StatusCode:   h.StatusCode,
				Title:        h.Title,
				Server:       h.Server,
				Technologies: h.Technologies,
				IsHTTPS:      h.IsHTTPS,
			})
		}
	}

	report.Stats = Stats{
		TotalSubdomains: len(results),
		LiveHTTP:        len(report.HTTP),
		CDNCount:        cdnCount,
		IPv6Count:       ipv6Count,
	}

	return report
}

// SaveJSON saves the report as formatted JSON
func SaveJSON(filename string, report *ScanReport) error {
	data, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(filename, data, 0644)
}

// SaveTXT saves results as a plain text list
func SaveTXT(filename string, report *ScanReport) error {
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintf(f, "# SubDiscover v2.0 - Akid's Global Cyber Security Tools © 2026\n")
	fmt.Fprintf(f, "# Domain: %s | Scanned: %s\n\n", report.Meta.Domain, report.Meta.ScanTime.Format(time.RFC3339))

	// Sort subdomains
	subs := make([]string, 0, len(report.Subdomains))
	for _, e := range report.Subdomains {
		subs = append(subs, e.Subdomain)
	}
	sort.Strings(subs)

	fmt.Fprintf(f, "[SUBDOMAINS - %d found]\n", len(subs))
	for _, s := range subs {
		fmt.Fprintf(f, "%s\n", s)
	}

	if len(report.HTTP) > 0 {
		fmt.Fprintf(f, "\n[LIVE HTTP - %d found]\n", len(report.HTTP))
		for _, h := range report.HTTP {
			fmt.Fprintf(f, "%s [%d] %s\n", h.URL, h.StatusCode, h.Title)
		}
	}

	if report.Assets != nil {
		fmt.Fprintf(f, "\n[DNS ASSETS]\n")
		for _, mx := range report.Assets.MX {
			fmt.Fprintf(f, "MX: %s (priority %d)\n", mx.Host, mx.Priority)
		}
		for _, ns := range report.Assets.NS {
			fmt.Fprintf(f, "NS: %s\n", ns)
		}
		for _, txt := range report.Assets.TXT {
			fmt.Fprintf(f, "TXT: %s\n", txt)
		}
	}

	return nil
}

// SaveMarkdown saves a pretty markdown report
func SaveMarkdown(filename string, report *ScanReport) error {
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintf(f, "# SubDiscover Report — %s\n\n", report.Meta.Domain)
	fmt.Fprintf(f, "> Generated by SubDiscover v%s | %s  \n", report.Meta.Version, report.Meta.Copyright)
	fmt.Fprintf(f, "> Scan Time: %s | Duration: %s\n\n", report.Meta.ScanTime.Format(time.RFC3339), report.Meta.Duration)

	fmt.Fprintf(f, "## Summary\n\n")
	fmt.Fprintf(f, "| Metric | Value |\n|--------|-------|\n")
	fmt.Fprintf(f, "| Subdomains Found | %d |\n", report.Stats.TotalSubdomains)
	fmt.Fprintf(f, "| Live HTTP/HTTPS | %d |\n", report.Stats.LiveHTTP)
	fmt.Fprintf(f, "| CDN-backed | %d |\n", report.Stats.CDNCount)
	fmt.Fprintf(f, "| IPv6 Enabled | %d |\n\n", report.Stats.IPv6Count)

	fmt.Fprintf(f, "## Subdomains (%d)\n\n", len(report.Subdomains))
	fmt.Fprintf(f, "| Subdomain | IPs | CDN | CNAMEs |\n|-----------|-----|-----|--------|\n")
	for _, s := range report.Subdomains {
		cdn := ""
		if s.IsCDN {
			cdn = "✓"
		}
		fmt.Fprintf(f, "| `%s` | %s | %s | %s |\n",
			s.Subdomain, strings.Join(s.IPs, ", "), cdn, strings.Join(s.CNAMEs, ", "))
	}

	if len(report.HTTP) > 0 {
		fmt.Fprintf(f, "\n## Live HTTP/HTTPS (%d)\n\n", len(report.HTTP))
		fmt.Fprintf(f, "| URL | Status | Title | Technologies |\n|-----|--------|-------|-------------|\n")
		for _, h := range report.HTTP {
			fmt.Fprintf(f, "| %s | %d | %s | %s |\n",
				h.URL, h.StatusCode, h.Title, strings.Join(h.Technologies, ", "))
		}
	}

	if report.Assets != nil && (len(report.Assets.MX) > 0 || len(report.Assets.NS) > 0) {
		fmt.Fprintf(f, "\n## DNS Assets\n\n")
		if len(report.Assets.NS) > 0 {
			fmt.Fprintf(f, "**Nameservers:** %s\n\n", strings.Join(report.Assets.NS, ", "))
		}
		if len(report.Assets.MX) > 0 {
			fmt.Fprintf(f, "**Mail Servers (MX):**\n")
			for _, mx := range report.Assets.MX {
				fmt.Fprintf(f, "- `%s` (priority %d)\n", mx.Host, mx.Priority)
			}
			fmt.Fprintf(f, "\n")
		}
		if len(report.Assets.TXT) > 0 {
			fmt.Fprintf(f, "**TXT Records:**\n")
			for _, txt := range report.Assets.TXT {
				fmt.Fprintf(f, "- `%s`\n", txt)
			}
		}
	}

	fmt.Fprintf(f, "\n---\n*Akid's Global Cyber Security Tools © 2026*\n")
	return nil
}
